[package]
name = "sway_workspace_names"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc = "0.10.1"
dirs = "2.0.2"
serde_yaml = "0.8.9"
structopt = "0.3.1"
